// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmiusvhroulhlyouakwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtaXVzdmhyb3VsaGx5b3Vha3dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NTE2MTQsImV4cCI6MjA2NjQyNzYxNH0.GdxYqEszYu39DmQVfKX3xGApIPSakfSCvdU3CLuTk-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);